theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
title: What is going on?
description: Have you ever thought to yourself "We should really know what is going on!"? Then this is your place.